(improvement): Current labeling in Chart tradingview
bitfinexcom/bfx-hf-ui-core pull request #182
Opened 2021-11-19 17:20 UTC by dmytroshch

ticket - https://app.asana.com/0/1125859137800433/1201393465655964

Added param uiID, which be shown as pair label in Chart
![Снимок экрана от 2021-11-19 19-07-40](https://user-images.githubusercontent.com/81973123/142663250-86cdcb36-dc38-4551-b987-5f0337f63b45.png)
![Снимок экрана от 2021-11-19 19-07-49](https://user-images.githubusercontent.com/81973123/142663252-19f09d92-eae2-4507-b9b3-79b1448da593.png)
![Снимок экрана от 2021-11-19 19-08-00](https://user-images.githubusercontent.com/81973123/142663255-38d84321-ba29-4755-9d70-e912cd699568.png)

2021-11-19 17:53 UTC, Blaumaus approved these changes

2021-11-22 08:41 UTC, bhoomij requested changes

2021-11-22 08:41 UTC, bhoomij commented on src/components/Chart/Chart.js
> +  const uiID = isPerp ? _uiID : `${getCurrencySymbol(base)}/${getCurrencySymbol(quote)}`
replace `${getCurrencySymbol(base)}/${getCurrencySymbol(quote)}` with 
`getPairFromMarket(market, getCurrencySymbol)` so its easily changed and maintained from one place when we want to update labelling in future

2021-11-23 07:45 UTC, bhoomij approved these changes

2021-11-23 07:45 UTC, merged