(fix) Balances: Added new context i18n key
bitfinexcom/bfx-hf-ui-core pull request #266
Opened 2022-01-27 13:30 UTC by dmytroshch

ticket - https://app.asana.com/0/1125859137800433/1201728494443765

2022-01-27 15:10 UTC, Blaumaus approved these changes

2022-02-02 05:55 UTC, bhoomij approved these changes

2022-02-02 05:57 UTC, bhoomij requested changes
it will be confusing to use same orderContexts namespace for both order/balance, please create separate one for balances

2022-02-03 07:32 UTC, bhoomij approved these changes

2022-02-08 10:40 UTC, bhoomij approved these changes

2022-02-08 10:40 UTC, merged