(improvement) Backtest options redesign
bitfinexcom/bfx-hf-ui-core pull request #461
Opened 2022-07-06 15:56 UTC by dmytroshch

### Asana task:
https://app.asana.com/0/home/1200372033295260/1202361351756054

### Description:
![Снимок экрана от 2022-07-06 18-55-14](https://user-images.githubusercontent.com/81973123/177592979-9116d475-36f4-4579-af62-2c3b556dfb0e.png)
![Снимок экрана от 2022-07-06 18-54-41](https://user-images.githubusercontent.com/81973123/177592991-e8435ffe-50eb-413a-a452-6efc250cafbe.png)
![Снимок экрана от 2022-07-07 12-21-59](https://user-images.githubusercontent.com/81973123/177739909-c4f93832-99c0-4382-bf44-6fcb6b099e35.png)

### Related Pull Requests:
...

### Backend Dependencies:
...

### Other Dependencies:
...

2022-07-06 16:23 UTC, Blaumaus approved these changes

2022-07-07 04:02 UTC, bhoomij requested changes

2022-07-07 04:02 UTC, bhoomij commented on src/components/BacktestOptionsPanel/BacktestOptionsPanel.js
> +            intent={Intent.INFO}
lets not have blue color for disabled state, either keep green with diff shade for disabled state or white/gray color

2022-07-07 10:19 UTC, bhoomij approved these changes

2022-07-07 10:19 UTC, merged