(improvement) Add smooth transition when switching between settings tabs
bitfinexcom/bfx-hf-ui-core pull request #511
Opened 2022-08-23 15:54 UTC by Blaumaus

### Asana task:
[Add smooth transition when switching between settings tabs](https://app.asana.com/0/1201849173362898/1202720041915739/f)

https://user-images.githubusercontent.com/35810911/186204644-0f3dde38-fc1c-4f64-910c-526b1e2cffd9.mp4

2022-08-23 15:59 UTC, bhoomij commented
@Blaumaus thanks for picking this.
Video reminds me to have custom vertical scrollbar(used across other places) for settings too. can you create a task for this ?

2022-08-23 16:00 UTC, Blaumaus commented
@bhoomij yes, I will

2022-08-23 16:04 UTC, bhoomij requested changes

2022-08-23 16:04 UTC, bhoomij commented on src/modals/AppSettingsModal/AppSettingsModal.js
> +        )}
can we reduce repeating code lines by making wrapper below, or any other better way

```
const Wrapper = ({ tab, children }) => (
isElectronApp && activeTab === tab && (
          <CSSTransition {...cssTransitionProps}>
            {children}
          </CSSTransition>
        )
)

<Wrapper tab=SETTINGS_TABS.General>
<GeneralTab />
</Wrapper>

```

2022-08-24 08:38 UTC, bhoomij approved these changes

2022-08-24 08:38 UTC, merged