(improvement) Update WS/API disconnection behavior
bitfinexcom/bfx-hf-ui-core pull request #530
Opened 2022-09-06 14:51 UTC by Blaumaus

### Asana task:
[Update WS/API disconnection behavior](https://app.asana.com/0/1201849173362898/1202543653121708/f)

### Description:
Using `data.client` event based on https://app.asana.com/0/0/1202547753013956/f

2022-09-06 19:41 UTC, dmytroshch requested changes
we have changed `data.client` message https://github.com/bitfinexcom/bfx-hf-server/pull/199

2022-09-07 08:43 UTC, dmytroshch commented
you can merge my branch

2022-09-07 09:33 UTC, bhoomij approved these changes

2022-09-08 12:37 UTC, bhoomij commented
@Blaumaus please fix the merge conflicts

2022-09-08 12:50 UTC, bhoomij approved these changes

2022-09-08 12:50 UTC, merged