(improvement) Showing ccy icons in Ticker/TickerList
bitfinexcom/bfx-hf-ui-core pull request #6
Opened 2021-07-22 10:14 UTC by dmytroshch

ticket - https://app.asana.com/0/1125859137800433/1200640784964124

![Снимок экрана от 2021-07-22 13-03-00](https://user-images.githubusercontent.com/81973123/126623852-8c5741dc-af24-4a12-ad87-e4c9470d0be2.png)

2021-07-22 11:48 UTC, Blaumaus approved these changes

2021-07-29 06:55 UTC, bhoomij requested changes
icon color looks different, when checked with bitfinex they use `filter` styles for brightness, please use those styles

<img width="1390" alt="Screenshot 2021-07-29 at 12 21 05 PM" src="https://user-images.githubusercontent.com/29878604/127445752-e12e07b2-8d22-4117-91fe-9f7e7a35487c.png">

2021-07-29 06:55 UTC, bhoomij commented on src/components/ExchangeInfoBar/style.scss
> +      height: 20px;
lets first release with 15px and then we can update if required

2021-07-29 06:55 UTC, bhoomij commented on src/components/ExchangeInfoBar/ExchangeInforBar.constants.js
>              <span className='price-unit'>
please rename price-unit since it seems not relevant with pair column

2021-07-29 06:55 UTC, bhoomij commented on src/components/ExchangeInfoBar/ExchangeInforBar.constants.js
> +            <span className='price-unit'>
rename price-unit here too

2021-07-29 13:54 UTC, dmytroshch commented
![Снимок экрана от 2021-07-29 16-53-57](https://user-images.githubusercontent.com/81973123/127504444-036ac150-f1ab-4a74-a123-dba17f292a63.png)

2021-07-29 13:55 UTC, dmytroshch commented
@bhoomij I think we need keep 30px considering this PR https://github.com/bitfinexcom/ufx-ui/pull/96

2021-07-30 06:41 UTC, bhoomij approved these changes

2021-07-30 06:43 UTC, bhoomij commented
@dmytroshch  can I merge this now, or it depends on bitfinexcom/ufx-ui#96 ?

2021-07-30 06:44 UTC, dmytroshch commented
> @dmytroshch can I merge this now, or it depends on [bitfinexcom/ufx-ui#96](https://github.com/bitfinexcom/ufx-ui/pull/96) ?

i think it is better merge after updating ufx-ui

2021-07-30 06:58 UTC, bhoomij commented
released https://github.com/bitfinexcom/ufx-ui/pull/98 with v10.0.1 @dmytroshch

2021-07-30 07:06 UTC, merged